<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jjhec
 * @subpackage model
 * @author     Jérôme SOMMET
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
}
