all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:data/jjhec.sqlite3'
      username: root
      password: null
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jjhec'
      username: root
      password: pass
dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=jjhec'
      username: root
      password: pass
#dev:
#  doctrine:
#    class: sfDoctrineDatabase
#    param:
#      dsn: 'sqlite:data/jjhec_dev.sqlite3'
#      username: root
#      password: null
