<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/13 21:43:12
sfConfig::add(array(
  'app_sfApplyPlugin_from' => array (
  'email' => 'jjhec@jjhec.local',
  'fullname' => 'the staff at jjhec.local',
),
));
