<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/02/13 21:43:13
return array (
  'default' => 
  array (
    'global' => 
    array (
      'check_functions_docblock' => true,
      'check_context_get_instance' => true,
      'check_plugins' => true,
      'check_compat10' => true,
      'ignored_objects' => 
      array (
        'application' => 
        array (
        ),
        'classes' => 
        array (
        ),
        'module' => 
        array (
        ),
        'action' => 
        array (
        ),
        'template' => 
        array (
        ),
        'partial' => 
        array (
        ),
        'layout' => 
        array (
        ),
      ),
    ),
    'project' => NULL,
    'application' => NULL,
    'classes' => 
    array (
      'grouping_limit' => 10,
    ),
    'module' => 
    array (
      'max_actions_count' => 20,
    ),
    'action' => 
    array (
      'max_code_length' => 50,
      'check_other_actions_call' => true,
    ),
    'template' => 
    array (
      'max_code_length' => 100,
      'check_empty' => true,
    ),
    'partial' => 
    array (
      'max_code_length' => 50,
      'check_empty' => true,
    ),
    'layout' => 
    array (
      'max_code_length' => 100,
      'check_empty' => true,
    ),
    'plugin' => 
    array (
      'to_parse' => 
      array (
      ),
      'assets_path' => 'web/sfProjectAnalyserPlugin',
    ),
  ),
);
