<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/13 21:43:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jjhec',
  'username' => 'root',
  'password' => 'pass',
  'name' => 'doctrine',
)),);
